# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lio/Desktop/stuff/waveblocks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lio/Desktop/stuff/waveblocks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lio/Desktop/stuff/waveblocks/CMakeFiles /home/lio/Desktop/stuff/waveblocks/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lio/Desktop/stuff/waveblocks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named waveblocks-static

# Build rule for target.
waveblocks-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 waveblocks-static
.PHONY : waveblocks-static

# fast build rule for target.
waveblocks-static/fast:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/build
.PHONY : waveblocks-static/fast

#=============================================================================
# Target rules for targets named test_cont_sqrt

# Build rule for target.
test_cont_sqrt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cont_sqrt
.PHONY : test_cont_sqrt

# fast build rule for target.
test_cont_sqrt/fast:
	$(MAKE) -f test/CMakeFiles/test_cont_sqrt.dir/build.make test/CMakeFiles/test_cont_sqrt.dir/build
.PHONY : test_cont_sqrt/fast

#=============================================================================
# Target rules for targets named test_eigenhdf

# Build rule for target.
test_eigenhdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eigenhdf
.PHONY : test_eigenhdf

# fast build rule for target.
test_eigenhdf/fast:
	$(MAKE) -f test/CMakeFiles/test_eigenhdf.dir/build.make test/CMakeFiles/test_eigenhdf.dir/build
.PHONY : test_eigenhdf/fast

#=============================================================================
# Target rules for targets named test_innerproduct

# Build rule for target.
test_innerproduct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_innerproduct
.PHONY : test_innerproduct

# fast build rule for target.
test_innerproduct/fast:
	$(MAKE) -f test/CMakeFiles/test_innerproduct.dir/build.make test/CMakeFiles/test_innerproduct.dir/build
.PHONY : test_innerproduct/fast

#=============================================================================
# Target rules for targets named anharmonic_1D

# Build rule for target.
anharmonic_1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 anharmonic_1D
.PHONY : anharmonic_1D

# fast build rule for target.
anharmonic_1D/fast:
	$(MAKE) -f examples/CMakeFiles/anharmonic_1D.dir/build.make examples/CMakeFiles/anharmonic_1D.dir/build
.PHONY : anharmonic_1D/fast

#=============================================================================
# Target rules for targets named harmonic_2D

# Build rule for target.
harmonic_2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harmonic_2D
.PHONY : harmonic_2D

# fast build rule for target.
harmonic_2D/fast:
	$(MAKE) -f examples/CMakeFiles/harmonic_2D.dir/build.make examples/CMakeFiles/harmonic_2D.dir/build
.PHONY : harmonic_2D/fast

#=============================================================================
# Target rules for targets named hawp_eval

# Build rule for target.
hawp_eval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hawp_eval
.PHONY : hawp_eval

# fast build rule for target.
hawp_eval/fast:
	$(MAKE) -f examples/CMakeFiles/hawp_eval.dir/build.make examples/CMakeFiles/hawp_eval.dir/build
.PHONY : hawp_eval/fast

#=============================================================================
# Target rules for targets named hawp_homogen

# Build rule for target.
hawp_homogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hawp_homogen
.PHONY : hawp_homogen

# fast build rule for target.
hawp_homogen/fast:
	$(MAKE) -f examples/CMakeFiles/hawp_homogen.dir/build.make examples/CMakeFiles/hawp_homogen.dir/build
.PHONY : hawp_homogen/fast

#=============================================================================
# Target rules for targets named hawp_inhomogen

# Build rule for target.
hawp_inhomogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hawp_inhomogen
.PHONY : hawp_inhomogen

# fast build rule for target.
hawp_inhomogen/fast:
	$(MAKE) -f examples/CMakeFiles/hawp_inhomogen.dir/build.make examples/CMakeFiles/hawp_inhomogen.dir/build
.PHONY : hawp_inhomogen/fast

#=============================================================================
# Target rules for targets named nonsense_2N_2D

# Build rule for target.
nonsense_2N_2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonsense_2N_2D
.PHONY : nonsense_2N_2D

# fast build rule for target.
nonsense_2N_2D/fast:
	$(MAKE) -f examples/CMakeFiles/nonsense_2N_2D.dir/build.make examples/CMakeFiles/nonsense_2N_2D.dir/build
.PHONY : nonsense_2N_2D/fast

#=============================================================================
# Target rules for targets named tunneling_1D

# Build rule for target.
tunneling_1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tunneling_1D
.PHONY : tunneling_1D

# fast build rule for target.
tunneling_1D/fast:
	$(MAKE) -f examples/CMakeFiles/tunneling_1D.dir/build.make examples/CMakeFiles/tunneling_1D.dir/build
.PHONY : tunneling_1D/fast

waveblocks/csv/coefficients_file_parser.o: waveblocks/csv/coefficients_file_parser.cpp.o
.PHONY : waveblocks/csv/coefficients_file_parser.o

# target to build an object file
waveblocks/csv/coefficients_file_parser.cpp.o:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/csv/coefficients_file_parser.cpp.o
.PHONY : waveblocks/csv/coefficients_file_parser.cpp.o

waveblocks/csv/coefficients_file_parser.i: waveblocks/csv/coefficients_file_parser.cpp.i
.PHONY : waveblocks/csv/coefficients_file_parser.i

# target to preprocess a source file
waveblocks/csv/coefficients_file_parser.cpp.i:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/csv/coefficients_file_parser.cpp.i
.PHONY : waveblocks/csv/coefficients_file_parser.cpp.i

waveblocks/csv/coefficients_file_parser.s: waveblocks/csv/coefficients_file_parser.cpp.s
.PHONY : waveblocks/csv/coefficients_file_parser.s

# target to generate assembly for a file
waveblocks/csv/coefficients_file_parser.cpp.s:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/csv/coefficients_file_parser.cpp.s
.PHONY : waveblocks/csv/coefficients_file_parser.cpp.s

waveblocks/util/complexnumber_parser.o: waveblocks/util/complexnumber_parser.cpp.o
.PHONY : waveblocks/util/complexnumber_parser.o

# target to build an object file
waveblocks/util/complexnumber_parser.cpp.o:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/util/complexnumber_parser.cpp.o
.PHONY : waveblocks/util/complexnumber_parser.cpp.o

waveblocks/util/complexnumber_parser.i: waveblocks/util/complexnumber_parser.cpp.i
.PHONY : waveblocks/util/complexnumber_parser.i

# target to preprocess a source file
waveblocks/util/complexnumber_parser.cpp.i:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/util/complexnumber_parser.cpp.i
.PHONY : waveblocks/util/complexnumber_parser.cpp.i

waveblocks/util/complexnumber_parser.s: waveblocks/util/complexnumber_parser.cpp.s
.PHONY : waveblocks/util/complexnumber_parser.s

# target to generate assembly for a file
waveblocks/util/complexnumber_parser.cpp.s:
	$(MAKE) -f CMakeFiles/waveblocks-static.dir/build.make CMakeFiles/waveblocks-static.dir/waveblocks/util/complexnumber_parser.cpp.s
.PHONY : waveblocks/util/complexnumber_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... doc"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... waveblocks-static"
	@echo "... test_cont_sqrt"
	@echo "... test_eigenhdf"
	@echo "... test_innerproduct"
	@echo "... anharmonic_1D"
	@echo "... harmonic_2D"
	@echo "... hawp_eval"
	@echo "... hawp_homogen"
	@echo "... hawp_inhomogen"
	@echo "... nonsense_2N_2D"
	@echo "... tunneling_1D"
	@echo "... waveblocks/csv/coefficients_file_parser.o"
	@echo "... waveblocks/csv/coefficients_file_parser.i"
	@echo "... waveblocks/csv/coefficients_file_parser.s"
	@echo "... waveblocks/util/complexnumber_parser.o"
	@echo "... waveblocks/util/complexnumber_parser.i"
	@echo "... waveblocks/util/complexnumber_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

